services:
  db:
    image: postgres:15-alpine
    container_name: points-open-db
    restart: always
    environment:
      POSTGRES_USER: klyb_user
      POSTGRES_PASSWORD: klyb_password
      POSTGRES_DB: points_open
    ports:
      - "5434:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
